---
title: "main_plot"
author: "anjie & gal"
date: "1/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(Metrics)

source(here("helper/simulation_results_processing.R"))

b_res <- read_csv(here("processed_rt_task_data.csv"))



nn_res <- readRDS(here("report_res/scaled_no_noise_res.RDS")) 
r_res <- readRDS(here("report_res/scaled_random_model.RDS"))
c_res <- readRDS(here("report_res/scaled_continuous_model_res.RDS"))

b_res_print <- b_res %>% 
  mutate(sequence_scheme = case_when(
    deviant_position == 2 ~ "BDBBBB", 
    deviant_position == 4 ~ "BBBDBB", 
    deviant_position == 6 ~ "BBBBBD", 
    TRUE ~ "BBBBBB", 
  ), 
  sequence_scheme_print = case_when(
    sequence_scheme == "BBBBBB" ~ "No Deviant", 
    sequence_scheme == "BDBBBB" ~ "Deviant at 2nd Trial", 
    sequence_scheme == "BBBDBB" ~ "Deviant at 4th Trial", 
    sequence_scheme == "BBBBBD" ~ "Deviant at Last Trial"
  ), 
  log_trial_looking_time = log(trial_looking_time)) %>% 
  separate(block_type, into = c("complexity", "similarity"), sep = "_") %>% 
  select(subject, complexity, trial_number, 
         sequence_scheme, sequence_scheme_print, trial_looking_time, log_trial_looking_time)


b_res_summary <- b_res_print %>% 
  group_by(trial_number, sequence_scheme, sequence_scheme_print, complexity) %>%
  summarise(
    trial_looking_time = mean(trial_looking_time), 
    log_trial_looking_time = mean(log_trial_looking_time)
  ) 

```


# main plots 

```{r eval=FALSE, include=FALSE}
viz_df <- bind_rows(nn_res, r_res, c_res) %>% 
  mutate(res_type = im_type, 
        res_val = scaled_log_sample_n) %>%
  select(res_type, complexity, trial_number, sequence_scheme_print, res_val) %>% 
  bind_rows(
    b_res_print %>% mutate(res_type = "behavioral", res_val = log_trial_looking_time) %>% 
      select(res_type, complexity, trial_number, sequence_scheme_print, res_val)
  ) %>% 
  mutate(res_type_print = case_when(
    res_type == "surprisal" ~ "Surprisal",
    res_type == "EIG_nn" ~ "No Noise", 
    res_type == "random" ~ "Random", 
    res_type == "EIG" ~ "EIG", 
    res_type == "KL" ~ "KL", 
    res_type == "behavioral" ~ "Behavioral"
  ))
b_res_print
```


```{r echo=FALSE}


library(patchwork)

viz_df$res_type_print <- factor(viz_df$res_type_print, levels = c("Behavioral", "EIG", "KL", "Surprisal", "No Noise", "Random"))
viz_df$sequence_scheme_print <- factor(viz_df$sequence_scheme_print, 
                                       levels = c("No Deviant",  "Deviant at 2nd Trial", 
                                                  "Deviant at 4th Trial", "Deviant at Last Trial"))




behavioral_plot <- viz_df %>% 
  filter(res_type_print == "Behavioral") %>% 
   ggplot(aes(x = trial_number, y = res_val, color = complexity)) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2),  fatten = 0) + 
   stat_summary(fun.data = "mean_cl_boot",
                geom = "line", position = position_dodge(width = .2)) +
  
  facet_grid(res_type_print~sequence_scheme_print) +
  scale_x_continuous(breaks = seq(1, 6, 1)) + 
  #langcog::theme_mikabr() +
  theme_classic()+
  langcog::scale_color_solarized(name = "Trial Complexity",labels = c("Complex", "Simple")) + 
  ylab("log-transformed looking time (s)") + 
  theme(strip.background = element_blank(), 
        axis.title.x = element_blank(), 
        axis.line.x = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none", 
        panel.border = element_rec(color = "black", fill = NA), 
        strip.text.x = element_text(size = 6),
        strip.text.y = element_text(size = 6)
        )

model_plot <- viz_df %>% 
  filter(res_type_print != "Behavioral") %>% 
  ggplot(aes(x = trial_number, y = res_val, color = complexity)) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2),  fatten = 0) + 
   stat_summary(fun.data = "mean_cl_boot",
                geom = "line", position = position_dodge(width = .2)) +
  
  facet_grid(res_type_print~sequence_scheme_print) +
  scale_x_continuous(breaks = seq(1, 6, 1)) + 
  #langcog::theme_mikabr() +
  theme_classic()+
  langcog::scale_color_solarized(name = "Trial Complexity",labels = c("Complex", "Simple")) + 
  xlab("Trial Number") + 
  ylab("log-transformed samples") + 
  theme(strip.background = element_blank(), 
        strip.text.x = element_blank(),
        legend.position = "bottom", 
        strip.text.x = element_text(size = 6),
        strip.text.y = element_text(size = 6))


behavioral_plot + model_plot + plot_layout(heights = c(1, 5))
```

```{r eval=FALSE, include=FALSE}

viz_df %>% 
  ggplot(aes(x = trial_number, y = res_val, color = complexity)) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
   stat_summary(fun.data = "mean_cl_boot",
                geom = "line", position = position_dodge(width = .2)) +
  
  facet_grid(res_type_print~sequence_scheme_print,scales = "free") +
  scale_x_continuous(breaks = seq(1, 6, 1)) + 
  #langcog::theme_mikabr() +
  theme_classic()+
  langcog::scale_color_solarized(name = "Trial Complexity",labels = c("Complex", "Simple")) + 
  xlab("Trial Number") + 
  ylab("")
```


# main table 

```{r include=FALSE}
scaled_eig_res_sum <- summarise_scaled_tidy_sim_res(c_res %>% filter(im_type == "EIG"))
scaled_kl_res_sum <- summarise_scaled_tidy_sim_res(c_res %>% filter(im_type == "KL"))
scaled_s_res_sum <- summarise_scaled_tidy_sim_res(c_res %>% filter(im_type == "surprisal"))
scaled_r_res_sum <- summarise_scaled_tidy_sim_res(r_res)
scaled_nn_res_sum <- summarise_scaled_tidy_sim_res(nn_res)

eig_sim_b_res <- scaled_eig_res_sum %>% 
  left_join(b_res_summary, by = c("trial_number", "sequence_scheme", "sequence_scheme_print", "complexity")) 
kl_sim_b_res <- scaled_kl_res_sum %>% 
  left_join(b_res_summary, by = c("trial_number", "sequence_scheme", "sequence_scheme_print", "complexity"))
s_sim_b_res <- scaled_s_res_sum %>% 
  left_join(b_res_summary, by = c("trial_number", "sequence_scheme", "sequence_scheme_print", "complexity"))
r_sim_b_res <- scaled_r_res_sum %>% 
  left_join(b_res_summary, by = c("trial_number", "sequence_scheme", "sequence_scheme_print", "complexity"))
nn_sim_b_res <- scaled_nn_res_sum %>% 
  left_join(b_res_summary, by = c("trial_number", "sequence_scheme", "sequence_scheme_print", "complexity"))



df_compare_eig <- calculate_scaled_correlation(eig_sim_b_res) %>% mutate(type = "Noisy Sampling Model (EIG)")
df_compare_kl <- calculate_scaled_correlation(kl_sim_b_res) %>% mutate(type = "Noisy Sampling Model (KL-divergence)")
df_compare_surpirsal <- calculate_scaled_correlation(s_sim_b_res) %>% mutate(type = "Noisy Sampling Model (Surprisal)")
df_compare_random <- calculate_scaled_correlation(r_sim_b_res) %>% mutate(type = "Random Sampling Model")
df_compare_nn <- calculate_scaled_correlation(nn_sim_b_res) %>% mutate(type = "No Noise Model (EIG)")

tb_df <- bind_rows(df_compare_eig, df_compare_kl, df_compare_surpirsal, df_compare_nn, df_compare_random) %>% 
  ungroup() %>% 
  mutate(r_in_log = round(r_in_log, 2), 
         rmse_in_log = round(rmse_in_log, 2)) %>% 
  mutate(`Pearson's r` = r_in_log, 
         "RMSE" = rmse_in_log) %>% 
  select(type, `Pearson's r`, RMSE) %>% 
  as.data.frame()
```


```{r echo=FALSE}
library(knitr)
library(kableExtra)

kable(
  tb_df,
  format = "latex",
  booktabs = TRUE,
  escape = FALSE,
  longtable = TRUE,
  col.names = c("Model Type (Linking Hypothesis)", "Pearson's r", "RMSE"),
  align = c("l", "c", "c"),
  caption = "Correlations and RMSE between different versions of the model and behavioral results"
  ) %>%
  row_spec(row = 0, align = "c") 

#%>%
  #footnote(
   # general_title = "Note.",
   # general = "haha",
    #threeparttable = TRUE,
    #footnote_as_chunk = TRUE
   # )
```




