---
title: "Habituation reflects optimal exploration over noisy perceptual samples"
bibliography: library.bib
csl: apa6.csl
document-params: "10pt, letterpaper"

author-information: > 
    \author{{\large \bf Morton Ann Gernsbacher (MAG@Macc.Wisc.Edu)} \\ Department of Psychology, 1202 W. Johnson Street \\ Madison, WI 53706 USA
    \AND {\large \bf Sharon J.~Derry (SDJ@Macc.Wisc.Edu)} \\ Department of Educational Psychology, 1025 W. Johnson Street \\ Madison, WI 53706 USA}

abstract: >
    From birth, humans constantly make decisions about what to look at and for how long. Yet the mechanism behind such decision-making remains poorly understood. Here we present the “rational action, noisy choice for habituation” (RANCH) model. RANCH is a rational learning model that takes noisy perceptual samples from stimuli and makes sampling decisions based on Expected Information Gain (EIG). The model captures three key patterns of looking time changes well documented in developmental research: habituation and dishabituation. We evaluated the model with adult looking time collected from a paradigm analogous to infant habituation paradigm. We compared RANCH with baseline models (no learning model, no perceptual noise model) and models with alternative linking hypotheses (Surprisal, KL-divergence). We showed that 1) learning and perceptual noise are critical assumptions of the model, and 2) Surprial and KL are good proxies for EIG under the current learning context. 

    
keywords: >
    decision making; learning; bayesian modeling; cognitive development 

    
output: 
    cogsci2016::cogsci_paper
    
  
nocite: | 
  @hunter1983effects, @bergmann2016development

#final-submission: \cogscifinalcopy
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=3, fig.height=3, fig.crop = F, 
                      fig.pos = "tb", fig.path='figs/',
                      echo=F, warning=F, cache=F, 
                      message=F, sanitize = T)
```

```{r, libraries}
library(tidyverse)
library(here)
library(lmerTest)
library(lme4)
library(patchwork)
library(Metrics)

library(png)
library(grid)
library(ggplot2)
library(xtable)
library(bookdown)

library(knitr)
library(kableExtra)


source(here("model/helper/simulation_results_processing.R"))

all_d <- read_csv(here("experiment/01_merged_data/merged_data.csv"))
d <- read_csv(here("experiment/02_processed_data/processed_rt_task_data.csv"))
d_complexity <- read_csv(here("experiment/02_processed_data/processed_complexity_data.csv"))

prolific <- read_csv(here("experiment/prolific.csv"))
exclusion_d <- read_csv(here("experiment/p_level_exclusion.csv"))


b_res <- read_csv(here("experiment/02_processed_data/processed_rt_task_data.csv"))


nn_res <- readRDS(here("model/report_res/scaled_no_noise_res.RDS")) 
r_res <- readRDS(here("model/report_res/scaled_random_model.RDS"))
c_res <- readRDS(here("model/report_res/scaled_continuous_model_res.RDS"))

b_res_print <- b_res %>% 
  mutate(sequence_scheme = case_when(
    deviant_position == 2 ~ "BDBBBB", 
    deviant_position == 4 ~ "BBBDBB", 
    deviant_position == 6 ~ "BBBBBD", 
    TRUE ~ "BBBBBB", 
  ), 
  sequence_scheme_print = case_when(
    sequence_scheme == "BBBBBB" ~ "No Deviant", 
    sequence_scheme == "BDBBBB" ~ "Deviant at 2nd Trial", 
    sequence_scheme == "BBBDBB" ~ "Deviant at 4th Trial", 
    sequence_scheme == "BBBBBD" ~ "Deviant at Last Trial"
  ), 
  log_trial_looking_time = log(trial_looking_time)) %>% 
  separate(block_type, into = c("complexity", "similarity"), sep = "_") %>% 
  select(subject, complexity, trial_number, 
         sequence_scheme, sequence_scheme_print, trial_looking_time, log_trial_looking_time)


b_res_summary <- b_res_print %>% 
  group_by(trial_number, sequence_scheme, sequence_scheme_print, complexity) %>%
  summarise(
    trial_looking_time = mean(trial_looking_time), 
    log_trial_looking_time = mean(log_trial_looking_time)
  ) 

```



# Introduction 


```{r child = "01_introduction.Rmd"}
```


# Experiment  


```{r child = "02_experiment.Rmd"}
```

# Model  

```{r child = "03_model.Rmd"}
```




# Alternative Models 


```{r child = "04_alternative_models.Rmd"}
```


# General discussion 

```{r child = "05_general_discussion.Rmd"}
```

<!--# Acknowledgements

Place acknowledgments (including funding information) in a section at
the end of the paper.
-->

# References 

```{r}
# References will be generated automatically by Pandoc and included here.
# The following code is some latex to format the bibliography. Do not remove it.
```



\setlength{\parindent}{-0.1in} 
\setlength{\leftskip}{0.125in}
\noindent
