---
output: pdf_document
---

The current work aimed to provide a computational model that can explain the three key phenomena observed in typical infant looking time paradigms: habituation, dishabituation, and complexity effect. RANCH assumes a rational learner that takes noisy perceptual samples from stimuli and makes sampling decisions based on expected information gain. We evaluated the model with adult looking time data collected from a paradigm that mirrors classic infant looking time paradigms. We found that RANCH can successfully reproduce the patterns observed in behavioral data. We find that other information theoretic quantities (e.g. KL-divergence and Surprisal) are good proxies for the rational learning policy. Moreover, by contrasting the model results with our baseline models, we showed that habituation, dishabituation, and complexity effects only arise in a learning model that takes into account the noisy nature of perception. 

The current work aimed to provide a computational model that can explain the key phenomena observed in typical infant looking time paradigms: habituation, dishabituation, and how these are modified by stimulus complexity. RANCH assumes a rational learner that takes noisy perceptual samples from stimuli and makes sampling decisions based on expected information gain. We evaluated the model with adult looking time data collected from a paradigm that mirrors classic infant looking time paradigms, in which participants are learning about multi-feature concepts. We found that RANCH can successfully reproduce the patterns observed in behavioral data. By contrasting the model results with our baseline models, we showed that habituation, dishabituation, and complexity effects only arise in a learning model that takes into account the noisy nature of perception. Moreover, we find that, in the current learning context, other information theoretic quantities (surprisal and KL-divergence) are good proxies for the rational linking hypothesis, EIG.

RANCH constitutes a significant step forward in the modeling of looking time in that it models the moment-to-moment decision making process of whether to keep sampling or look away. This is in contrast to previous approaches, which incremented time in steps of whole stimuli, and therefore can merely correlate information-theoretic variability in the stimulus sequence to look-away probability and looking time. Our mechanistic account of the sampling process depended on assuming that perception is noisy, which made it necessary to take multiple samples from a stimulus until the information content of the stimulus has been learned. The moment-to-moment increments in which RANCH operates also enabled us to perform the rational analysis of human behavior in the current paradigm by using EIG as the linking hypothesis between learning and sampling.

The similarity between model fits among models with different linking hypotheses highlights the significance of learning contexts. Our results should not be interpreted as evidence showing that the three linking hypotheses are indistinguishable across all learning contexts. Previous work has shown that adopting surprisal as learning policy can lead to undesirable behaviors in artificial agents [e.g. “the white noise problem”, @oudeyer2007intrinsic]. Moreover, the two alternative linking hypotheses are backward-looking metrics that utilize past heuristics to make decisions. This characteristic could lead to them only working when the environment is stable and the cost of sampling is low. Since human exploration is sensitive to environmental complexity, a forward-looking metric like EIG might be particularly suitable to predict behaviors in a more dynamic and realistic learning context [@dubey2020reconciling; @vogelstein2022prospective].

There are several limitations to our work. For our behavioral data, one concern is that adult looking time might not be driven by the same process underpinning infant looking time. Adult looking might be driven by task-preparation, rather than intrinsic interests. Nevertheless, across the three conditions with different filler tasks, we found no differences in looking time patterns. This suggests that adult looking time is unlikely to be related to the task. In regards to the model, a few concerns can be raised about the current implementation. First of all, the current stimulus representation is rather oversimplified, using an unweighted collection of binary features. In addition, RANCH assumes that the EIG from the environment is a constant throughout the experiment, but one can argue that environmental EIG might increase as the experiment progresses (e.g. the longer you haven’t attended to the things in your surrounding, the more interesting they become). While implementing more sophisticated assumptions could potentially explain additional variance in the data, our current work suggests that even a simple rational learner that takes noisy samples from a set of independent binary features is capable of explaining key phenomena in looking time change. 

Our ultimate goal is to provide a rational learner model that can account for information seeking behaviors through the lens of infants’ looking time. Here we have shown that such a model can reproduce habituation, dishabituation, and complexity effects. Moving forward, we aim to capture and explain more contentious phenomena documented in the infant looking time literature such as familiarity preferences and age effects (Hunter & Ames, 1988). Our ongoing work with infants will eventually enable us to evaluate our model with developmental data. When combined with adult results, the data and model will provide insights into the general mechanisms through which learners decide what to look at, and when to stop looking.
